name: Publish Core Package

on:
  push:
    tags:
      - 'v*'  # v1.0.0, v1.0.1 gibi version tag'lerde çalışır
  release:
    types: [created]
  workflow_dispatch:  # Manuel tetikleme için

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://npm.pkg.github.com'
          
      - name: Publish package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}  # Repository secret kullanıyoruz 